package com.example.smartpantrymanager;

import android.content.*; import android.database.Cursor; import android.database.sqlite.*; import java.util.*;

public class PantryDatabaseHelper extends SQLiteOpenHelper {
 private static final String DB="smart_pantry.db"; private static final int VER=4;
 public static final String TABLE_PANTRY="pantry", COLUMN_ID="id", COLUMN_NAME="ingredient_name", COLUMN_QUANTITY="quantity", COLUMN_UNIT="unit", COLUMN_EXPIRY_DATE="expiry_date";
 public PantryDatabaseHelper(Context c){super(c,DB,null,VER);}
 @Override public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE pantry (id INTEGER PRIMARY KEY AUTOINCREMENT, ingredient_name TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL, expiry_date TEXT)");createRecipeTables(d);seed(d);}
 private void createRecipeTables(SQLiteDatabase d){d.execSQL("CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, method TEXT NOT NULL)");d.execSQL("CREATE TABLE recipe_ingredients (id INTEGER PRIMARY KEY AUTOINCREMENT, recipe_id INTEGER NOT NULL, ingredient_name TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL)");}
 @Override public void onUpgrade(SQLiteDatabase d,int old,int n){if(old<3){d.execSQL("DROP TABLE IF EXISTS recipe_ingredients");d.execSQL("DROP TABLE IF EXISTS recipes");createRecipeTables(d);seed(d);}else if(old<4){d.delete("recipe_ingredients",null,null);d.delete("recipes",null,null);seed(d);}}
 private void seed(SQLiteDatabase d){
  String[][] a={
   {"Chicken Curry","Heat the oil in a pot and fry the onion until soft and golden. Add the ginger garlic paste and cook for 1 minute. Add the curry powder and tomatoes and cook until the tomatoes soften. Add the chicken and salt and cook for about 8 minutes. Add the potatoes and water. Cover and simmer for 25–30 minutes until the chicken and potatoes are cooked. Garnish with coriander.","chicken|500|g;potato|2|piece;onion|1|piece;tomato|2|piece;oil|2|tbsp;curry powder|2|tbsp;ginger garlic paste|1|tbsp;salt|1|tsp;water|1|cup;coriander|2|tbsp"},
   {"Creamy Chicken Pasta","Boil the pasta in salted water until al dente and drain. Cut the chicken into pieces and season with paprika, salt and pepper. Melt the butter in a pan and fry the chicken until golden and cooked through. Add garlic and cook for 30 seconds. Pour in the cream and simmer gently for 3–4 minutes. Stir in Parmesan, then add the pasta. Toss until coated and finish with parsley. This follows the basic TikTok-style creamy chicken pasta method of cooking the chicken, building the cream-and-cheese sauce in the same pan, then combining it with pasta. TikTok Shop","chicken breast|400|g;penne pasta|250|g;fresh cream|250|ml;garlic|3|clove;parmesan cheese|0.5|cup;butter|2|tbsp;paprika|1|tsp;salt|1|tsp;black pepper|0.5|tsp;parsley|2|tbsp"},
   {"Garlic Butter Chicken","Cut the chicken into bite-sized pieces. Season with paprika, salt and pepper. Heat the oil in a pan and fry the chicken until golden. Reduce the heat and add butter and garlic. Stir in the honey and lemon juice. Cook for another 2–3 minutes until the sauce coats the chicken. Sprinkle with parsley and serve.","chicken breast|500|g;butter|3|tbsp;garlic|4|clove;paprika|1|tsp;salt|1|tsp;black pepper|0.5|tsp;lemon juice|2|tbsp;honey|1|tbsp;parsley|2|tbsp;oil|1|tbsp"},
   {"Chicken Alfredo","Cook the fettuccine until al dente. Season the chicken with salt, pepper and Italian seasoning. Melt 1 tbsp butter in a pan and cook the chicken until golden, then slice it. Add the remaining butter and garlic to the pan. Pour in the cream and simmer gently. Add Parmesan and stir until smooth. Toss in the pasta, top with chicken and sprinkle with parsley.","fettuccine|250|g;chicken breast|400|g;fresh cream|250|ml;parmesan cheese|1|cup;butter|2|tbsp;garlic|3|clove;salt|1|tsp;black pepper|0.5|tsp;italian seasoning|1|tsp;parsley|2|tbsp"},
   {"Honey Garlic Chicken","Cut the chicken into cubes and coat with cornflour, pepper and paprika. Heat oil in a pan and cook the chicken until crispy and cooked through. Mix honey, soy sauce, garlic and water. Pour the mixture over the chicken. Simmer for 3–5 minutes until thick and sticky. Garnish with spring onion.","chicken breast|500|g;honey|0.25|cup;soy sauce|0.25|cup;garlic|4|clove;cornflour|2|tbsp;oil|2|tbsp;black pepper|0.5|tsp;paprika|1|tsp;water|0.25|cup;spring onion|2|tbsp"},
   {"Chicken Fried Rice","Dice the chicken and fry it in 1 tbsp oil until cooked. Remove it from the pan. Add the remaining oil and garlic, followed by diced carrot and peas. Push the vegetables aside and scramble the eggs. Add the cooked rice and chicken. Pour over the soy sauce, season with pepper and stir-fry over high heat for 3–4 minutes. Add spring onion before serving.","cooked rice|3|cup;chicken breast|300|g;egg|2|piece;carrot|1|piece;frozen peas|0.5|cup;soy sauce|3|tbsp;garlic|2|clove;oil|2|tbsp;spring onion|2|piece;black pepper|0.5|tsp"},
   {"Cheesy Chicken Wrap","Slice the chicken and season with paprika, garlic powder and salt. Heat oil in a pan and fry until cooked and slightly crispy. Warm the tortillas. Spread mayonnaise over each wrap and add lettuce, tomato, chicken and cheese. Fold tightly. Toast each wrap in a dry pan for 1–2 minutes per side until golden and the cheese melts.","chicken breast|400|g;tortilla wraps|4|piece;cheddar cheese|1|cup;mayonnaise|0.25|cup;lettuce|1|cup;tomato|1|piece;paprika|1|tsp;garlic powder|1|tsp;salt|0.5|tsp;oil|1|tbsp"},
   {"Spaghetti Bolognese","Cook the spaghetti according to the packet instructions. Heat oil and fry the onion until soft. Add garlic and beef mince and cook until browned. Stir in tomato paste, chopped tomatoes, Italian seasoning, salt and pepper. Reduce the heat and simmer for 15–20 minutes. Serve the sauce over the spaghetti.","spaghetti|250|g;beef mince|500|g;onion|1|piece;garlic|3|clove;chopped tomatoes|400|g;tomato paste|2|tbsp;oil|2|tbsp;italian seasoning|1|tsp;salt|1|tsp;black pepper|0.5|tsp"},
   {"Creamy Garlic Mushroom Pasta","Cook the pasta until al dente. Melt butter in a pan and fry sliced mushrooms until browned. Add garlic and Italian seasoning. Pour in the cream and simmer gently for 3 minutes. Add Parmesan and stir until melted. Season with salt and pepper. Add the pasta and toss thoroughly. Garnish with parsley.","pasta|250|g;mushrooms|250|g;fresh cream|250|ml;garlic|4|clove;butter|2|tbsp;parmesan|0.5|cup;salt|1|tsp;black pepper|0.5|tsp;italian seasoning|1|tsp;parsley|2|tbsp"},
   {"Chicken Quesadillas","Slice the chicken, pepper and onion. Season the chicken with paprika, cumin and salt. Heat oil and cook the chicken until almost done. Add the pepper and onion and cook until tender. Place chicken mixture and cheese over half of each tortilla and fold it over. Toast in a dry pan for 2–3 minutes on each side. Cut into triangles and serve with sour cream.","chicken breast|400|g;tortillas|4|piece;cheddar cheese|1.5|cup;bell pepper|1|piece;onion|1|piece;paprika|1|tsp;cumin|1|tsp;salt|0.5|tsp;oil|1|tbsp;sour cream|0.5|cup"},
   {"Crispy Chicken Tenders","Slice the chicken into strips. Season the flour with paprika, garlic powder, salt and pepper. Whisk the eggs with milk. Coat each chicken strip in flour, then egg mixture and finally breadcrumbs. Heat the oil over medium heat. Fry the tenders in batches until golden brown and completely cooked through, about 4–6 minutes depending on thickness. Drain on paper towel.","chicken breast|500|g;flour|1|cup;egg|2|piece;breadcrumbs|1.5|cup;paprika|1|tsp;garlic powder|1|tsp;salt|1|tsp;black pepper|0.5|tsp;milk|0.25|cup;oil|2|cup"},
   {"Loaded Potato Wedges","Preheat the oven to 200°C. Cut the potatoes into wedges and coat with oil, paprika, garlic powder, salt and pepper. Arrange on a baking tray and bake for 35–45 minutes, turning halfway. Sprinkle cheddar and mozzarella over the wedges and return to the oven until melted. Top with sour cream and chopped spring onion.","potato|4|piece;oil|2|tbsp;paprika|1|tsp;garlic powder|1|tsp;salt|1|tsp;black pepper|0.5|tsp;cheddar cheese|1|cup;sour cream|0.5|cup;spring onion|2|piece;mozzarella|0.5|cup"},
   {"Chocolate Chip Cookies","Preheat the oven to 180°C. Cream the softened butter with both sugars until smooth. Beat in the egg and vanilla. In another bowl, combine flour, baking soda, salt and cornflour. Gradually mix the dry ingredients into the butter mixture. Fold in the chocolate chips. Scoop balls of dough onto a lined tray and bake for about 10–12 minutes until the edges are golden. Allow them to cool before removing.","flour|2|cup;butter|170|g;brown sugar|0.75|cup;white sugar|0.5|cup;egg|1|piece;vanilla essence|2|tsp;baking soda|1|tsp;salt|0.5|tsp;chocolate chips|1.5|cup;cornflour|1|tbsp"},
   {"Fudgy Chocolate Brownies","Preheat the oven to 175°C. Melt the butter and dark chocolate together and allow to cool slightly. Whisk the eggs with both sugars and vanilla. Slowly mix in the melted chocolate. Fold in the flour, cocoa powder and salt, then add chocolate chips. Pour into a lined baking tin. Bake for approximately 25–30 minutes. The centre should remain slightly fudgy. Cool before cutting.","butter|150|g;dark chocolate|150|g;white sugar|1|cup;brown sugar|0.5|cup;egg|3|piece;flour|0.75|cup;cocoa powder|0.25|cup;vanilla essence|1|tsp;salt|0.5|tsp;chocolate chips|0.5|cup"},
   {"Cinnamon Rolls","Warm the milk until lukewarm and stir in yeast and white sugar. Leave for 5–10 minutes. Mix with the egg, half the butter and flour to form a soft dough. Knead until smooth and allow to rise for about 1 hour. Roll into a rectangle. Spread with the remaining butter and sprinkle with brown sugar and cinnamon. Roll tightly, slice and place in a baking dish. Rise for another 30 minutes. Bake at 180°C for 20–25 minutes. Mix cream cheese and icing sugar and spread over the warm rolls.","flour|3|cup;milk|1|cup;yeast|2.25|tsp;white sugar|0.25|cup;butter|80|g;egg|1|piece;brown sugar|0.5|cup;cinnamon|2|tbsp;icing sugar|1|cup;cream cheese|100|g"},
   {"Lotus Biscoff Cheesecake Cups","Crush the biscuits and combine them with melted butter. Press the mixture into the bottoms of serving cups. Beat the cream cheese, icing sugar, vanilla and lemon juice until smooth. Whip the fresh cream separately until thick, then fold it into the cream-cheese mixture. Melt the Biscoff spread slightly and fold some into the filling. Spoon the cheesecake mixture into the cups. Top with melted Biscoff spread, white chocolate and biscuit crumbs. Refrigerate for at least 4 hours.","lotus biscoff biscuits|200|g;butter|70|g;cream cheese|250|g;fresh cream|250|ml;icing sugar|0.5|cup;biscoff spread|0.5|cup;vanilla essence|1|tsp;lemon juice|1|tbsp;white chocolate|50|g;biscoff crumbs|0.25|cup"},
   {"Oreo Chocolate Mug Cake","Crush the Oreos finely in a microwave-safe mug. Add flour, cocoa powder, sugar and baking powder and mix. Add milk, oil and vanilla and stir until you have a smooth batter. Mix in the chocolate chips. Place the Nutella in the centre and gently cover it with batter. Microwave for approximately 60–90 seconds, checking after 60 seconds. Let it stand for 1 minute before eating.","oreo biscuits|4|piece;flour|3|tbsp;cocoa powder|1|tbsp;sugar|2|tbsp;baking powder|0.25|tsp;milk|4|tbsp;oil|1|tbsp;vanilla essence|0.5|tsp;chocolate chips|2|tbsp;nutella|1|tbsp"}
  };
  for(String[] x:a){ContentValues v=new ContentValues();v.put("name",x[0]);v.put("method",x[1]);long id=d.insert("recipes",null,v);for(String s:x[2].split(";")){String[] p=s.split("\\|");ContentValues q=new ContentValues();q.put("recipe_id",id);q.put("ingredient_name",p[0]);q.put("quantity",Double.parseDouble(p[1]));q.put("unit",p[2]);d.insert("recipe_ingredients",null,q);}}
 }
 public long addIngredient(Ingredient i){return getWritableDatabase().insert(TABLE_PANTRY,null,values(i));} public int updateIngredient(Ingredient i){return getWritableDatabase().update(TABLE_PANTRY,values(i),COLUMN_ID+"=?",new String[]{""+i.getId()});} public int deleteIngredient(long id){return getWritableDatabase().delete(TABLE_PANTRY,COLUMN_ID+"=?",new String[]{""+id});}
 private ContentValues values(Ingredient i){ContentValues v=new ContentValues();v.put(COLUMN_NAME,i.getName());v.put(COLUMN_QUANTITY,i.getQuantity());v.put(COLUMN_UNIT,i.getUnit());v.put(COLUMN_EXPIRY_DATE,i.getExpiryDate());return v;}
 public List<Ingredient> getAllIngredients(){List<Ingredient> r=new ArrayList<>();try(Cursor c=getReadableDatabase().query(TABLE_PANTRY,null,null,null,null,null,COLUMN_NAME+" COLLATE NOCASE")){while(c.moveToNext())r.add(new Ingredient(c.getLong(c.getColumnIndexOrThrow(COLUMN_ID)),c.getString(c.getColumnIndexOrThrow(COLUMN_NAME)),c.getDouble(c.getColumnIndexOrThrow(COLUMN_QUANTITY)),c.getString(c.getColumnIndexOrThrow(COLUMN_UNIT)),c.getString(c.getColumnIndexOrThrow(COLUMN_EXPIRY_DATE))));}return r;}
 public List<Recipe> getMatchingRecipes(){List<Recipe> r=new ArrayList<>();List<Ingredient> pantry=getAllIngredients();for(Recipe x:all())if(canMake(x,pantry))r.add(x);return r;} public Recipe getRecipe(long id){for(Recipe r:all())if(r.getId()==id)return r;return null;}
 private List<Recipe> all(){List<Recipe> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,method FROM recipes ORDER BY name",null)){while(c.moveToNext()){List<Recipe.RequiredIngredient> q=new ArrayList<>();try(Cursor z=getReadableDatabase().query("recipe_ingredients",null,"recipe_id=?",new String[]{""+c.getLong(0)},null,null,"id")){while(z.moveToNext())q.add(new Recipe.RequiredIngredient(z.getString(z.getColumnIndexOrThrow("ingredient_name")),z.getDouble(z.getColumnIndexOrThrow("quantity")),z.getString(z.getColumnIndexOrThrow("unit"))));}out.add(new Recipe(c.getLong(0),c.getString(1),q,c.getString(2)));}}return out;}
 private boolean canMake(Recipe r,List<Ingredient> p){for(Recipe.RequiredIngredient x:r.getIngredients()){double total=0;for(Ingredient i:p)if(norm(i.getName()).equals(norm(x.name))&&compatible(i.getUnit(),x.unit))total+=convert(i.getQuantity(),i.getUnit(),x.unit);if(total<x.quantity)return false;}return true;}
 private String norm(String s){s=s.toLowerCase(Locale.US).replaceAll("[^a-z0-9]"," ").trim().replaceAll("\\s+"," ");if(s.endsWith("ies"))s=s.substring(0,s.length()-3)+"y";else if(s.endsWith("s")&&!s.endsWith("ss"))s=s.substring(0,s.length()-1);return s;}
 private String group(String s){s=norm(s);if(s.equals("g")||s.equals("gram")||s.equals("grams"))return "g";if(s.equals("kg")||s.equals("kilogram"))return "kg";if(s.equals("ml")||s.equals("milliliter")||s.equals("millilitre"))return "ml";if(s.equals("l")||s.equals("liter")||s.equals("litre"))return "l";if(s.equals("tsp")||s.equals("teaspoon")||s.equals("tbsp")||s.equals("tablespoon"))return "spoon";if(s.equals("piece")||s.equals("item")||s.equals("slice")||s.equals("clove")||s.equals("can")||s.equals("pinch"))return s;return s;}
 private boolean compatible(String a,String b){String x=group(a),y=group(b);return x.equals(y)||(x.equals("kg")&&y.equals("g"))||(x.equals("g")&&y.equals("kg"))||(x.equals("l")&&y.equals("ml"))||(x.equals("ml")&&y.equals("l"))||(x.equals("spoon")&&y.equals("spoon"));}
 private double convert(double n,String a,String b){String x=group(a),y=group(b);if(x.equals(y)&&x.equals("spoon")&&norm(a).equals("tablespoon")&&norm(b).equals("teaspoon"))return n*3;if(x.equals(y)&&x.equals("spoon")&&norm(a).equals("teaspoon")&&norm(b).equals("tablespoon"))return n/3;if(x.equals("kg")&&y.equals("g"))return n*1000;if(x.equals("g")&&y.equals("kg"))return n/1000;if(x.equals("l")&&y.equals("ml"))return n*1000;if(x.equals("ml")&&y.equals("l"))return n/1000;return n;}
}
