package com.example.smartpantrymanager;

import android.content.*; import android.database.Cursor; import android.database.sqlite.*; import java.util.*;

public class PantryDatabaseHelper extends SQLiteOpenHelper {
 private static final String DB="smart_pantry.db"; private static final int VER=3;
 public static final String TABLE_PANTRY="pantry", COLUMN_ID="id", COLUMN_NAME="ingredient_name", COLUMN_QUANTITY="quantity", COLUMN_UNIT="unit", COLUMN_EXPIRY_DATE="expiry_date";
 public PantryDatabaseHelper(Context c){super(c,DB,null,VER);}
 @Override public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE pantry (id INTEGER PRIMARY KEY AUTOINCREMENT, ingredient_name TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL, expiry_date TEXT)"); createRecipeTables(d); seed(d);}
 private void createRecipeTables(SQLiteDatabase d){d.execSQL("CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, method TEXT NOT NULL)");d.execSQL("CREATE TABLE recipe_ingredients (id INTEGER PRIMARY KEY AUTOINCREMENT, recipe_id INTEGER NOT NULL, ingredient_name TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL)");}
 @Override public void onUpgrade(SQLiteDatabase d,int old,int n){if(old<3){d.execSQL("DROP TABLE IF EXISTS recipe_ingredients");d.execSQL("DROP TABLE IF EXISTS recipes");createRecipeTables(d);seed(d);}}
 private void seed(SQLiteDatabase d){String[][] a={{"Tomato Pasta","Boil pasta. Saute garlic and tomato in oil, season, and combine.","pasta|200|g;tomato|2|piece;garlic|2|clove;olive oil|2|tbsp;salt|1|tsp"},{"Omelette","Whisk eggs and milk, cook in a hot pan, and fold.","egg|2|piece;milk|30|ml;salt|1|pinch;pepper|1|pinch"},{"Chicken Salad","Cook chicken, chop vegetables, toss together.","chicken|200|g;lettuce|100|g;tomato|1|piece;olive oil|1|tbsp;salt|1|pinch"},{"Pancakes","Mix batter and cook spoonfuls until golden.","flour|150|g;milk|200|ml;egg|1|piece;sugar|2|tbsp"},{"Rice and Beans","Cook rice, saute onion, add beans, and serve.","rice|200|g;beans|1|can;onion|1|piece;salt|1|pinch"},{"Grilled Cheese","Butter bread, add cheese, and grill until golden.","bread|2|slice;cheese|50|g;butter|1|tbsp"},{"Vegetable Soup","Chop vegetables and simmer until tender.","carrot|2|piece;potato|2|piece;onion|1|piece;water|500|ml;salt|1|tsp"},{"Fruit Smoothie","Blend all ingredients until smooth.","banana|1|piece;milk|250|ml;honey|1|tbsp"},{"Garlic Bread","Mix garlic and butter, spread on bread, and bake.","bread|4|slice;garlic|2|clove;butter|2|tbsp"},{"Tuna Sandwich","Mix tuna and mayonnaise, add lettuce, and assemble.","bread|2|slice;tuna|1|can;mayonnaise|2|tbsp;lettuce|50|g"},{"Mashed Potato","Boil potatoes, mash with butter and milk.","potato|500|g;butter|2|tbsp;milk|100|ml;salt|1|tsp"},{"French Toast","Dip bread in egg mixture and fry both sides.","bread|2|slice;egg|1|piece;milk|50|ml;cinnamon|1|tsp"},{"Bean Salad","Chop vegetables and toss with beans and oil.","beans|1|can;tomato|1|piece;onion|1|piece;olive oil|1|tbsp"},{"Chicken Rice","Cook chicken and rice with seasoned onion.","chicken|200|g;rice|200|g;onion|1|piece;salt|1|pinch"},{"Tomato Soup","Simmer ingredients and blend until smooth.","tomato|4|piece;onion|1|piece;water|500|ml;salt|1|tsp"},{"Egg Fried Rice","Stir-fry rice with egg, peas, and soy sauce.","rice|250|g;egg|2|piece;peas|100|g;soy sauce|1|tbsp"},{"Avocado Toast","Mash avocado onto toasted bread and season.","bread|2|slice;avocado|1|piece;salt|1|pinch;lemon|1|piece"}};for(String[] x:a){ContentValues v=new ContentValues();v.put("name",x[0]);v.put("method",x[1]);long id=d.insert("recipes",null,v);for(String s:x[2].split(";")){String[] p=s.split("\\|");ContentValues q=new ContentValues();q.put("recipe_id",id);q.put("ingredient_name",p[0]);q.put("quantity",Double.parseDouble(p[1]));q.put("unit",p[2]);d.insert("recipe_ingredients",null,q);}}}
 public long addIngredient(Ingredient i){return getWritableDatabase().insert(TABLE_PANTRY,null,values(i));} public int updateIngredient(Ingredient i){return getWritableDatabase().update(TABLE_PANTRY,values(i),COLUMN_ID+"=?",new String[]{""+i.getId()});} public int deleteIngredient(long id){return getWritableDatabase().delete(TABLE_PANTRY,COLUMN_ID+"=?",new String[]{""+id});}
 private ContentValues values(Ingredient i){ContentValues v=new ContentValues();v.put(COLUMN_NAME,i.getName());v.put(COLUMN_QUANTITY,i.getQuantity());v.put(COLUMN_UNIT,i.getUnit());v.put(COLUMN_EXPIRY_DATE,i.getExpiryDate());return v;}
 public List<Ingredient> getAllIngredients(){List<Ingredient> r=new ArrayList<>();try(Cursor c=getReadableDatabase().query(TABLE_PANTRY,null,null,null,null,null,COLUMN_NAME+" COLLATE NOCASE")){while(c.moveToNext())r.add(new Ingredient(c.getLong(c.getColumnIndexOrThrow(COLUMN_ID)),c.getString(c.getColumnIndexOrThrow(COLUMN_NAME)),c.getDouble(c.getColumnIndexOrThrow(COLUMN_QUANTITY)),c.getString(c.getColumnIndexOrThrow(COLUMN_UNIT)),c.getString(c.getColumnIndexOrThrow(COLUMN_EXPIRY_DATE))));}return r;}
 public List<Recipe> getMatchingRecipes(){List<Recipe> r=new ArrayList<>();List<Ingredient> pantry=getAllIngredients();for(Recipe x:all())if(canMake(x,pantry))r.add(x);return r;} public Recipe getRecipe(long id){for(Recipe r:all())if(r.getId()==id)return r;return null;}
 private List<Recipe> all(){List<Recipe> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,method FROM recipes ORDER BY name",null)){while(c.moveToNext()){List<Recipe.RequiredIngredient> q=new ArrayList<>();try(Cursor z=getReadableDatabase().query("recipe_ingredients",null,"recipe_id=?",new String[]{""+c.getLong(0)},null,null,"id")){while(z.moveToNext())q.add(new Recipe.RequiredIngredient(z.getString(z.getColumnIndexOrThrow("ingredient_name")),z.getDouble(z.getColumnIndexOrThrow("quantity")),z.getString(z.getColumnIndexOrThrow("unit"))));}out.add(new Recipe(c.getLong(0),c.getString(1),q,c.getString(2)));}}return out;}
 private boolean canMake(Recipe r,List<Ingredient> p){for(Recipe.RequiredIngredient x:r.getIngredients()){double total=0;for(Ingredient i:p)if(norm(i.getName()).equals(norm(x.name))&&compatible(i.getUnit(),x.unit))total+=convert(i.getQuantity(),i.getUnit(),x.unit);if(total<x.quantity)return false;}return true;}
 private String norm(String s){s=s.toLowerCase(Locale.US).replaceAll("[^a-z0-9]"," ").trim().replaceAll("\\s+"," ");if(s.endsWith("ies"))s=s.substring(0,s.length()-3)+"y";else if(s.endsWith("s")&&!s.endsWith("ss"))s=s.substring(0,s.length()-1);return s;}
 private String group(String s){s=norm(s);if(s.equals("g")||s.equals("gram")||s.equals("grams"))return "g";if(s.equals("kg")||s.equals("kilogram"))return "kg";if(s.equals("ml")||s.equals("milliliter")||s.equals("millilitre"))return "ml";if(s.equals("l")||s.equals("liter")||s.equals("litre"))return "l";if(s.equals("tsp")||s.equals("teaspoon")||s.equals("tbsp")||s.equals("tablespoon"))return "spoon";if(s.equals("piece")||s.equals("item")||s.equals("slice")||s.equals("clove")||s.equals("can")||s.equals("pinch"))return s;return s;}
 private boolean compatible(String a,String b){String x=group(a),y=group(b);return x.equals(y)||(x.equals("kg")&&y.equals("g"))||(x.equals("g")&&y.equals("kg"))||(x.equals("l")&&y.equals("ml"))||(x.equals("ml")&&y.equals("l"))||(x.equals("spoon")&&y.equals("spoon"));}
 private double convert(double n,String a,String b){String x=group(a),y=group(b);if(x.equals(y)&&x.equals("spoon")&&norm(a).equals("tablespoon")&&norm(b).equals("teaspoon"))return n*3;if(x.equals(y)&&x.equals("spoon")&&norm(a).equals("teaspoon")&&norm(b).equals("tablespoon"))return n/3;if(x.equals("kg")&&y.equals("g"))return n*1000;if(x.equals("g")&&y.equals("kg"))return n/1000;if(x.equals("l")&&y.equals("ml"))return n*1000;if(x.equals("ml")&&y.equals("l"))return n/1000;return n;}
}
